### ISSUE TITLE
Improvements: Direct buy & progress bar

### ISSUE THREAD

**Issue by Rido** [jerodev/chrome-ibood-tracker#1]
Hi Jeroen,

Great work, it's a nice Chrome extension. I have a few suggestions for the extension that would make it (a lot) better:
1. Add a button "Direct buy" like the website: http://iboodhunt.1dagskoopjes.nl/
2. Show a progress bar when I click on the extension button

Thanks!

**Comment by wterbeek** [comment]
Hi Jeroen,

nice work! 

would it be possible to store, client side ofcourse, the login data so that when the hunt is active the extension would login automatically? It would, in my opinion be an extra option to support the direct by button as suggested by rido

**Comment by jerodev** [comment]
@Rido I have added an option in the latest commit to add keywords. When a product matches these keywords, the product page will automaticly open in your browser. I am working on opening the order page automaticly, but iBood has some anoying checks in place.
The new option will be available in the next release on the Chrome Store.

@wterbeek Please open a new issue for your question, this keeps things easy to track for me. ;)

**Comment by jerodev** [comment]
An option to display the stock in a hunt has now been added.
