### ISSUE TITLE
Use the JSON files to retrieve the data

### ISSUE THREAD

**Issue by Rido** [jerodev/chrome-ibood-tracker#4]
Hi Jeroen,

I checked the network console and saw that iBOOD retrieves the data via JSON files. Maybe it is an idea to use these JSON files instead of parsing the HTML.

Current product: http://feeds.ibood.com/nl/offer.jsonp?c=o&_=1448463683352
Product stock: http://feeds.ibood.com/nl/stock.jsonp?c=s&_=1448463683351

These last numbers are some random/time integers.

**Comment by jerodev** [comment]
This is a good idea.
I had been looking into something like this to reduce the request size, but I could get the hunt status from these json results. This has been fixed now by doing the hunt check in another function.
